//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSchedule
    {
        public int Id { get; set; }
        public string Day { get; set; }
        public int CourseId { get; set; }
        public int TrainerId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string Description { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Room Room { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
